### ISSUE TITLE
Add Settings Menu

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/MSEdgeRedirect#13]
- [ ] Move "Start with Windows"
    - [ ] Add "Start with no Icon"
- [ ] Add "Check for Updates on Startup"
- [ ] Add drop downs for alternatives - #9

**Comment by rcmaehl** [comment]
"Added" with `/change` flag. Due to release deadlines, pushing back to 0.6.0.0

**Comment by gnpaone** [comment]
> * [ ]  Move "Start with Windows"
>   
>   * [ ]  Add "Start with no Icon"
> * [ ]  Add "Check for Updates on Startup"
> * [ ]  Add drop downs for alternatives - [Add ability to choose what gets redirected #9](https://github.com/rcmaehl/MSEdgeRedirect/issues/9)
![143726370-11db7483-9db0-4121-9db4-5a5fbfcbf414](https://user-images.githubusercontent.com/78990165/145739488-f932801f-a05f-48a2-b107-3091eab0b0e4.png)
I've just noticed that the options to change search engine is in install menu, please add it in this settings menu instead so that it will be easy to switch with one click without installer

**Comment by rcmaehl** [comment]
Added with `/settings` flag. Will update menu to control the application.
