### ISSUE TITLE
Redirect start/search menu web results to google?

### ISSUE THREAD

**Issue by rp1231** [rcmaehl/MSEdgeRedirect#166]
### Description of the new feature / enhancement

Would it be possible to redirect search queries (web results) from the start/search menu to google?

### Scenario when this would be used?

There are some queries like currency conversion that I like to use that google provides better results for.
For eg. If you type in 123 usd, the result on the panel on the side will return a value in your native currency as one of the top results.
But if you type in $123, the same result is not obtained via the bing results on the side.
And bing messes up the currencies sometimes, like it'll convert 123(native currency) to usd instead of 123 usd to native currency.
But google search is much better at such queries.

This is based on my experience on win11, I don't know if it is the same case in win10.

**Comment by rcmaehl** [comment]
Are you referring to these results where it doesn't open a web browser at all?

![image](https://user-images.githubusercontent.com/716581/184996318-090a98cb-bb5f-4c62-8073-81bac98c0366.png)

If so, unfortunately, these aren't *currently* modifiable. Although another dev and I are working on trying to get this sorted out.

**Comment by Axer128** [comment]
Related:
Windows 11 current stable release (2200.856)
Pressing windows key + W, brings up the web search, with a bunch of widgets showing it in by default (mainly news and weather)
if I simply type in a search than hit return, such as final fantasy.
It opens in chrome, with bing, despite default search engine and MSEedgeRedirect settings set to google. It does show it will do this (shows final fantasy - bing search)
below that link are some suggestions:
final fantasy 14
final fantasy 7
etc
If I instead click final fantasy 7, it does indeed use google. I get to this url as desired:
https://www.google.com/search?q=final%20fantasy%207&qs=AS&pq=final%20fantasy&sk=AS2&sc=5-13&cc=US&setLang=en-US&FORM=U627SB&pc=U627

Possibly unrelated to this app: Many, but not all of the default news widgets, if I click them , instead of going to the news article they usually go to a page like this:
https://www.google.com/url?q=https://www.yahoo.com/lifestyle/good-news-yellowstone-fans-season-204400722.html
The page you were on is trying to send you to https://www.yahoo.com/lifestyle/good-news-yellowstone-fans-season-204400722.html.

 If you do not want to visit that page, you can [return to the previous page](https://www.google.com/url?q=https://www.yahoo.com/lifestyle/good-news-yellowstone-fans-season-204400722.html#).

Useless page.. Probably I can fix these with a tampermonkey script, but yea weird it does that.

Neither a big deal as I don't care for this widge and figured it would be something startallback would disable.. But it does not so I left it on. I sometimes just block the key combo with autohotkey and have it do something else useful (minimize active window). But yea worth noting for ppl who do like this functionality.

**Comment by rcmaehl** [comment]
Closing for now. This isn't achievable currently, but I'm always keeping an eye out and experimenting. It will be implemented if ever figured out.
