### ISSUE TITLE
Revamp Edge Removal Detection

### ISSUE THREAD

**Issue by direrFlood** [rcmaehl/MSEdgeRedirect#173]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [ ] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

1_) install the lastest edge removal. [@AveYo](https://github.com/AveYo)'s [Edge Removal](https://github.com/AveYo/fox/blob/main/Edge_Removal.bat)
2) run microsoft-edge:gooogle.com
3) it does not open anything.

### ✔️ Expected Behavior

open google chrome on google.com website

### ❌ Actual Behavior

does not open anything

### Microsoft Windows version

windows 11 pro 21h2( 22000.856)

### Other Software

[@AveYo](https://github.com/AveYo)'s [Edge Removal](https://github.com/AveYo/fox/blob/main/Edge_Removal.bat) 
[2022.08.23 V9 stable](https://github.com/AveYo/fox/commit/42d2792f9f82ec9a837836d71fef45a64152f682)

**Comment by rcmaehl** [comment]
I recently received feedback from AveYo in regards to this I'll be implementing to fix this.

**Comment by AveYo** [comment]
Figure this is a fitting place to announce that I've done some changes!

**Edge_Removal.bat** now exports BHO to `%SystemDrive%\Scripts` folder i.e. `C:\Scripts\ie_to_edge_stub.exe`
This is in part due to malware analysis shenanigans (lame Sigma rules).

**ChrEdgeFkOff.cmd** now rebranded as **OpenWebSearch.cmd** (old link still kept as-is).
_Tho I still retain my opinion that Microsoft Edge Chromium Based Browser and the way it's pushed IS vulgar_.

**Comment by rcmaehl** [comment]
> Figure this is a fitting place to announce that I've done some changes!
> 
> **Edge_Removal.bat** now exports BHO to `%SystemDrive%\Scripts` folder i.e. `C:\Scripts\ie_to_edge_stub.exe` This is in part due to malware analysis shenanigans (lame Sigma rules).
> 
> **ChrEdgeFkOff.cmd** now rebranded as **OpenWebSearch.cmd** (old link still kept as-is). _Tho I still retain my opinion that Microsoft Edge Chromium Based Browser and the way it's pushed IS vulgar_.

Yep. Working on incorporating those to 0.8.0.0!
