### ISSUE TITLE
Redirect on task manager

### ISSUE THREAD

**Issue by CodeDoctorDE** [rcmaehl/MSEdgeRedirect#176]
### Description of the new feature / enhancement

![image](https://user-images.githubusercontent.com/20452814/188258434-2135efc9-8e43-42bf-bcf9-73d681d47986.png)
When clicking on "Online suchen" (Search online) you will be redirected to bing.

### Scenario when this would be used?

When trying to search what a progam do

**Comment by rcmaehl** [comment]
It appears this is using the default browser (https://) instead of edge specifically (microsoft-edge://). I'll eventually be adding something to address this in a seperate app called [AppLockerPlus](https://github.com/rcmaehl/AppLockerPlus).

**Comment by CodeDoctorDE** [comment]
Nice thanks

**Comment by Axer128** [comment]
Noticed this too.
In the meantime you could use this script I wrote that is just a dumb redirect of all bing searches to google:
https://greasyfork.org/en/scripts/452361-bing-to-google-auto-redirect

(Tested on chrome + tampermonkey, but should work on any browser/userscript manager since its fairly simple)
