### ISSUE TITLE
why you keep updating this software as it is pretty straight forward. this raises security concerns that you keeps updating it.

### ISSUE THREAD

**Issue by direrFlood** [rcmaehl/MSEdgeRedirect#199]
**Describe the request**
A clear and concise description of what the request is.

**Screenshots**
If applicable, add screenshots to help explain your request.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Build [e.g. 22494]

**Additional context**
Add any other context about the request here.

**Comment by rcmaehl** [comment]
If you're asking why I release updates in general, it's because

- Microsoft KBs change command line parameters breaking the app
- Some features haven't been implemented (Stocks, Traffic) to prevent them from loading MSN

If you're looking for less updates and just Edge -> Default Browser without extra features check out AveYo's [OpenWebSearch](https://github.com/AveYo/fox/blob/main/OpenWebSearch.cmd)

**Comment by Tom-Evers** [comment]
Maybe this would be a good place to note: the constant popups about the IFEO updates? I can tell you from experience: nobody cares about little minor updates that are logically required to keep the product running. Everybody cares about annoying popups.

Do those updates silently, in the background, without user confirmation. Or at least give users the option to disable the popups.

**Comment by rcmaehl** [comment]
> Maybe this would be a good place to note: the constant popups about the IFEO updates? I can tell you from experience: nobody cares about little minor updates that are logically required to keep the product running. Everybody cares about annoying popups.
> 
> Do those updates silently, in the background, without user confirmation. Or at least give users the option to disable the popups.

Yep, coming in 0.8.0.0
