### ISSUE TITLE
Provide option to DE-embed Windows Specific "Apps" (E.g. TikTok, Twitter, Wikipedia)

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/MSEdgeRedirect#20]
https://www.reddit.com/r/techsupport/comments/r3tuyb/edge_windows_11_default_browser/

**Comment by rcmaehl** [comment]
Okay so Microsoft is just literally embedding the website into a wrapper. Google play banned this shit YEARS ago. Thankfully, it looks like there is a fallback URL that can be used.

![image](https://user-images.githubusercontent.com/716581/143978314-4b43ed5e-5953-432b-bdcd-78efc8e20532.png)

**Comment by HarshalKudale** [comment]
Well I looked into it a bit ,it turns out url from apps aren't calling msedge.exe for those links. Basically those apps are behaving like tabs in edge Brower (msedge_no_ifeo.exe) in your case. you cant get URL by grabbing msedge.exe arguments. To open those URLs from apps in default Brower the app must be opened in default browser.
