### ISSUE TITLE
Open pdfs with edge

### ISSUE THREAD

**Issue by Nirgranth** [rcmaehl/MSEdgeRedirect#234]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

Managed Update (Chocolatey, Winget, Etc)

### Install Mode

Active Mode

### Steps to reproduce

Try to open pdf with edge as default pdf viewer

### ✔️ Expected Behavior

Open PDF

### ❌ Actual Behavior

![image](https://user-images.githubusercontent.com/48947296/210178333-63ef6a19-20dd-4de6-86d7-76e171c26e98.png)

### Microsoft Windows version

22H2 (OS Build 22621.963)

**Comment by rcmaehl** [comment]
Please try this with version 0.7.3.0

**Comment by kevinoid** [comment]
I'm not the original reporter, but I was experiencing this issue with [0.7.2.0](https://github.com/rcmaehl/MSEdgeRedirect/releases/tag/0.7.2.0) and **am not experiencing it** with [0.7.3.0](https://github.com/rcmaehl/MSEdgeRedirect/releases/tag/0.7.3.0).  Seems fixed to me.  Thanks @rcmaehl!

While testing I noticed that the PDF drop-down in settings only has "Default" and "Custom" options, no option for "Chrome".  (Choosing "Custom" and browsing to chrome.exe works fine.)  Not sure if that's expected behavior.  Let me know if you'd like me to open an issue for it.

**Comment by rcmaehl** [comment]
> I'm not the original reporter, but I was experiencing this issue with [0.7.2.0](https://github.com/rcmaehl/MSEdgeRedirect/releases/tag/0.7.2.0) and **am not experiencing it** with [0.7.3.0](https://github.com/rcmaehl/MSEdgeRedirect/releases/tag/0.7.3.0). Seems fixed to me. Thanks @rcmaehl!
> 
> While testing I noticed that the PDF drop-down in settings only has "Default" and "Custom" options, no option for "Chrome". (Choosing "Custom" and browsing to chrome.exe works fine.) Not sure if that's expected behavior. Let me know if you'd like me to open an issue for it.

This is expected behavior. I'll be revamping a lot of the settings in the next couple months actually. "Default" just uses the default PDF handler becaues it was requested in #148

**Comment by Nirgranth** [comment]
Works now
