### ISSUE TITLE
WSA bug

### ISSUE THREAD

**Issue by LK024** [rcmaehl/MSEdgeRedirect#301]
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

Manual Update

### Install Mode

Service Mode

### Steps to reproduce

When WSA is installed the first search/link after boot open WSA and not chrome

### ✔️ Expected Behavior

That Chrome will launched

### ❌ Actual Behavior

It open WSA, and after the launch of WSA chrome is opened

### Microsoft Windows version

23H2 (build SO 22631.2129)

**Comment by vonDubenshire** [comment]
> When WSA is installed the first search/link after boot open WSA and not chrome

This is happening for me again.

> Version	22H2
> Installed on	‎11/‎29/‎2023
> **OS build**	**23595.1001**
> Experience	Windows Feature Experience Pack 1000.23595.1001.0

![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/40748193/38868ceb-b7ea-42b6-a673-7169e4f8b09c)

**Comment by vvirtues** [comment]
WSA is discontinued and no longer available

**Comment by rcmaehl** [comment]
Yeah, closing as won't fix

**Comment by TheShark27** [comment]
I found a definitive fix after a day troubleshooting this.

1. **Make sure WSA is turned off** before proceeding.
2. **Navigate to the following registry location** in Windows Registry Editor:
   ```
   Computer\HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\SystemAppData\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\AppUriHandlers\
   ```
3. **Delete the problematic site keys** under the `AppUriHandlers` folder. For example, delete the `google.com` key if it's causing issues.

### How to Test:
1. In **Google Chrome**, type `microsoft-edge:google.com` in the address bar **while WSA is turned off**.
2. Before the fix, this should open Google through WSA.
3. After the fix, a dialog should pop up asking whether to open with **WSA** or **Chrome**. Select **Chrome**.
4. The first time you do this, it might open a strange XML file, but on the second attempt, the link will work correctly in Chrome.

Just to be sure it won't happen again, I deleted the entire AppUriHandlers folder, so that other links, such as amazon.com, won't open in WSA anymore.
