### ISSUE TITLE
Allow User selection of Monitoring Rate - Service Mode

### ISSUE THREAD

**Issue by bgreganti** [rcmaehl/MSEdgeRedirect#36]
**Check List**
- [X] The App appears in the system tray
- [ ] Running `microsoft-edge:https://google.com` redirects successfully

**Describe the bug**\
I often leave a few pages open in Edge on another monitor. Redirect doesn't work in this case and the links from say the lock screen open in Edge instead. I understand if this is intended or can't redirected, but would be nice.

**To Reproduce**
1. Open Edge.
2. Press Win + R
3. Enter "microsoft-edge:https://google.com"
4. Press Ok.

**⚠️ File Upload ⚠️**

1. Leave edge open
2. Open Powershell
3. Run `gwmi Win32_Process | where { $_.name -like "msedge*.exe"} | Select-Object CommandLine | Format-Table -Wrap -AutoSize | Out-File $env:LOCALAPPDATA\MSEdgeRedirect\logs\edge.txt`
4. Open %localappdata%\MSEdgeRedirect\logs
5. Attach the log files

**Desktop (please complete the following information):**
 - Windows Version: 21H1
 - Windows Build: 19043.1415

**Additional context**\

**Comment by rcmaehl** [comment]
I have two possible recommendations:

- Use an InPrivate Window for those tabs
- Uninstall MSEdgeRedirect and Reinstall with Admin Rights, Select Active Mode

Active Mode is a lot more reliable when there's an existing edge window. This is because the command line parameters get lost when they're added as a new tab to an existing window.

I'm working on improving this but I can't be too agressive with monitoring or CPU usage noteably increases. Perhaps I'll add a slider to allow people to make the choice themselves.

**Comment by rcmaehl** [comment]
Service mode has been improved to capture Edge earlier. Monitor rate slider will not be implemented
