### ISSUE TITLE
Please update Chocolatey package to latest version

### ISSUE THREAD

**Issue by CeSium58** [rcmaehl/MSEdgeRedirect#436]
### Preflight Checklist

- [ ] Microsoft Edge is selected in any "How do you want to open this?" box
- [ ] I've ran the [Cleanup tool](https://raw.githubusercontent.com/rcmaehl/MSEdgeRedirect/main/Assets/Cleanup%20Tool.ps1) and tried another install

### Install Type

N/A

### Install Mode

Active Mode

### ℹ Behavior

Please update Chocolatey package to latest version

### Microsoft Windows version

-

### Other Software

-

**Comment by micwoj92** [comment]
ping @Smart123s @gnpaone

**Comment by gnpaone** [comment]
Apparently 0.7.5.0 is the last uploaded version in chocolatey. @rcmaehl can you please manually trigger the [chocolatey workflow](https://github.com/rcmaehl/MSEdgeRedirect/actions/workflows/chocolatey-package.yml) to analyse the logs since previous logs have been deleted. Probably CHOCO_KEY has been expired and this secret key needs to be regenerated and updated

**Comment by gnpaone** [comment]
UPDATE: Actually nothing wrong with the workflow but even then I have removed unnecessary code.

The problem is the package already exists but got rejected by choco due to some checksum issues. Should re-publish the package
![image](https://github.com/user-attachments/assets/401581cf-d193-4a06-a408-2cdbd854fb73)
![image](https://github.com/user-attachments/assets/942ef1f3-5438-487c-9f90-8e41671cb001)

@CeSium58 For now latest version can be installed using `choco install msedgeredirect --version 0.7.5.3 -y`

**Comment by Smart123s** [comment]
I have sent a message to Choco admins asking them to change the package
status from rejected to submitted of v0.7.5.3, so we can upload a new nupkg.

**Comment by gnpaone** [comment]
The problem has been solved. 0.7.5.3 version will soon be listed and available to the public via choco repo.

**Comment by Smart123s** [comment]
Was there anything you had to change, or did you just re-push the package?

**Comment by gnpaone** [comment]
I just re-pushed the package. I already posted my tests in chocolatey Google groups few weeks back and they responded to that [thread](https://groups.google.com/d/msgid/chocolatey/537d94b2-de03-4cf2-8fd2-67fc1bb12e54n%40googlegroups.com?utm_medium=email&utm_source=footer) and changed package status at the same time. For some reason their systems used wrong checksum to verify instead of the one in the pushed install.ps1
